### ISSUE TITLE
Google Login  - "refreshToken" error

### ISSUE THREAD

**Issue by cmdigital** [YodasMyDad/Dialogue#93]
I specified the ID, secret and redirect URI of my Google app.

I figured that the redirect URI is:
www.mywebsite.com/umbraco/Surface/GoogleOAuthSurface/GoogleLogin

When I am redirected back to the forum, after clicking 'Allow' in the Google Screen...

I get the the following error in red at the top of the forum page:
**Unable to get user information
Parameter "refreshToken" cannot be NULL or empty Parameter name: refreshToken**

I am not sure if I am missing something...

Help appreciated!

Carlos

**Comment by JohnBergman** [comment]
Did you look at the pull request?  I think that might have a fix, or conversely, are you using the code from the pull request?

**Comment by cmdigital** [comment]
I am using the version that comes from installing it from
**Developer/Packages**
in my Umbraco instance...

**Comment by JohnBergman** [comment]
I am assuming 1.0 then.  FWIW, I've been using the 2.0 beta and it seems pretty solid, a couple minor things, but maybe your issue is fixed in that code base

**Comment by cmdigital** [comment]
I am using 1.1 actually...
I will try 2.0 and report back here.
Thank you very much!

**Comment by cmdigital** [comment]
With the current version this issue is gone! 
Is there a way to create a local package from the Dialogue VS studio? Sorry... I am new to Umbraco...

(I'd like to push this update to my testing server...)

**Comment by JohnBergman** [comment]
There is a download that contains the package, to install it, all you would need to do is use the "install local" option and then drag the package you download onto it.  Its basically the same as from the "store" but the package is the .zip you download.  Also, some have had issues installing local, if you do, try a different browser (for example on my windows10 box I had to use chrome because IE and EDGE simply wouldn't do it)

Glad its working for you

**Comment by cmdigital** [comment]
Many thanks!
